# move_base parameter file


TrajectoryPlannerROS:
  #Independent settings for the local costmap
  transform_tolerance: 0.3
  sim_time: 5.0
  sim_granularity: 0.25
  sim_angular_granularity: 0.01 
  dwa: true
  vx_samples: 5 
  vtheta_samples: 20 
  max_vel_x: 5.0 # increased maximum allowed velocity
  min_vel_x: 0.1
  max_rotational_vel: 2.0
  min_in_place_rotational_vel: 0.0
  xy_goal_tolerance: 0.5 
  yaw_goal_tolerance: 1.5 
  goal_distance_bias: 24 # chosen after extensive testing and internet searches
  gdist_scale: 24 # equivalent dwa parameter
  path_distance_bias: 32 # chosen after extensive testing and internet searches
  pdist_scale: 32 # equivalent dwa parameter
  occdist_scale: 0.001 # obstacle avoidance reduced to fit through the door while still avoiding  obstacles
  heading_lookahead: 0.325 
  oscillation_reset_dist: 0.05 
  holonomic_robot: false
  acc_lim_th: 2.5 
  acc_lim_x: 2.5 
  acc_lim_y: 2.5 
  escape_vel: -1.0
  heading_scoring: true
  heading_scoring_timestep: 0.8
  holonomic_robot: false
  simple_attractor: false
  publish_cost_grid_pc: true

