obstacle_range: 2.5 #earlier recognition of obstacles
raytrace_range: 5 #earlier deletion of obstacles
footprint: [[0.33, 0.30], [0.33, -0.30], [-0.33, -0.30], [-0.33, 0.30]] # increased width to introduce tolerance

inflation_radius: 3 #create costs in entire map for smoother trajectories
cost_scaling_factor: 5.5 # costs with diminished exponential decay(default 6.5) to increase overall costs
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}



