obstacle_range: 1.05
raytrace_range: 2.5
footprint: [[0.33, 0.22], [0.33, -0.22], [-0.33, -0.22], [-0.33, 0.22]]
inflation_radius: 1.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#obstacle_range: 1.05
#raytrace_range: 2.5
#footprint: [[0.33, 0.22], [0.33, -0.22], [-0.33, -0.22], [-0.33, #0.22]]
#inflation_radius: 3.0
#cost_scaling_factor: 6.5
#observation_sources: laser_scan_sensor
#laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: #scan, marking: true, clearing: true}
